name: deaca
services:
  front:
    container_name: deacafront
    build:
      context: ./front
      target: development
    restart: unless-stopped
    user: node
    command: sh -c "npm i && npm start"
    tty: true
    volumes:
      - ./:/front
      - deaca.front.node_modules:/front/node_modules
      - deaca.front.angular:/front/.angular
  api:
    build:
      context: ./api
      target: development
    container_name: deacaapi
    user: node:node
    tty: true
    command: sh -c "npm install  && npm run dev"
    environment:
      - ${PGHOST}:${PGHOST}
      - ${PGPORT}:${PGPORT}
      - ${PGDATABASE}:${PGDATABASE}
      - ${PGUSER}:${PGUSER}
      - ${PGPASSWORD}:${PGPASSWORD}
    depends_on:
      db:
        condition: service_healthy
    volumes:
      # todo el proyecto al volumen para poder usar git dentro del contenedor.
      - ./:/api
      - deaca.api.node_modules:/api/node_modules
    restart: unless-stopped
    ports:
      - 3000:3000
  db:
    image: postgres:17-alpine
    container_name: deacadb
    restart: unless-stopped
    command: postgres -p ${PGPORT}
    environment:
      POSTGRES_USER: ${PGUSER}
      POSTGRES_PASSWORD: ${PGPASSWORD}
      POSTGRES_DB: ${PGDATABASE}
    ports:
      - ${PGPORT}:${PGPORT}
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U $${PGUSER} -d $${PGDATABASE}"]
      interval: 5s
      timeout: 5s
      retries: 5
    volumes:
      - ./db:/docker-entrypoint-initdb.d

# Hacemos volumenes nombrados para que las dependencias no se almacenen en local
# No se creen nuevos volumenes cada vez que levantamos los contenedoresPero que los podemos
# Pero que los podamos borrar con docker volume prune (borra todos los volumenes que haya)
# Esta forma es más eficiente que tener node_modules en el host, sobre todo si es una carpeta
# en el sistema de archivos de windows.
volumes:
  deaca.api.node_modules:
  deaca.front.node_modules:
  deaca.front.angular:

# TODO: Definir networks separadas?
