-- división administrativa
CREATE TABLE IF NOT EXISTS departamentos (
    id_departamento INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nombre CITEXT NOT NULL UNIQUE CHECK (
        char_length(nombre) BETWEEN 2 AND 32
    ),
    departamento CITEXT NOT NULL UNIQUE CHECK (
        char_length(departamento) BETWEEN 2 AND 32
        AND departamento ~ '^[a-zA-Z0-9-]+$' 
    )
);

DROP TRIGGER IF EXISTS tg_departamentos_departamento_inmutable ON departamentos;
CREATE TRIGGER tg_departamentos_departamento_inmutable
BEFORE UPDATE OF departamento ON departamentos
FOR EACH ROW
EXECUTE FUNCTION tr_fn_impedir_cambio_columna('departamento');