-- división administrativa
CREATE TABLE IF NOT EXISTS departamentos (
    id_departamento INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nombre CITEXT NOT NULL UNIQUE CHECK (
        char_length(nombre) BETWEEN 2 AND 32
    ),
    departamento CITEXT NOT NULL UNIQUE CHECK (
        char_length(departamento) BETWEEN 2 AND 32
        AND departamento ~ '^[a-zA-Z0-9-]+$' 
    )-- TODO: TRIGGER para asegurarse que no se cambia el departamento
);

CREATE TABLE IF NOT EXISTS localidades (
    id_localidad INTEGER PRIMARY KEY, -- El id de ideuy
    id_departamento INTEGER NOT NULL REFERENCES departamentos(id_departamento) ON DELETE CASCADE ON UPDATE CASCADE,
    nombre CITEXT NOT NULL CHECK (
        char_length(nombre) BETWEEN 2 AND 32
    ),
    localidad CITEXT NOT NULL UNIQUE CHECK (
        char_length(localidad) BETWEEN 2 AND 32
        AND localidad ~ '^[a-zA-Z0-9-]+$' 
    ),-- TODO: TRIGGER para asegurarse que no se cambia el localidad?
    UNIQUE(nombre, id_departamento)
);