-- división administrativa
CREATE TABLE IF NOT EXISTS departamentos (
    id_departamento INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nombre CITEXT NOT NULL UNIQUE CHECK (
        char_length(nombre) >= 2 AND 
        char_length(nombre) <= 100
    )
);

CREATE TABLE IF NOT EXISTS localidades (
    id_localidad INTEGER PRIMARY KEY, -- El id de ideuy
    id_departamento INTEGER NOT NULL REFERENCES departamentos(id_departamento) ON DELETE CASCADE ON UPDATE CASCADE,
    nombre CITEXT NOT NULL CHECK (
        char_length(nombre) >= 2 AND 
        char_length(nombre) <= 100
    ),
    UNIQUE(nombre, id_departamento)
);