-- división administrativa
CREATE TABLE IF NOT EXISTS departamentos (
    id_departamento INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nombre VARCHAR(50) NOT NULL UNIQUE
);

CREATE TABLE IF NOT EXISTS localidades (
    id_localidad INTEGER PRIMARY KEY, -- El id de ideuy
    id_departamento INTEGER NOT NULL REFERENCES departamentos(id_departamento) ON DELETE CASCADE ON UPDATE CASCADE,
    nombre VARCHAR(100) NOT NULL,
    UNIQUE(nombre, id_departamento)
);