CREATE TABLE IF NOT EXISTS localidades (
    id_localidad INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    id_departamento INTEGER NOT NULL REFERENCES departamentos(id_departamento) ON DELETE CASCADE ON UPDATE CASCADE,
    id_externo INTEGER,
    nombre CITEXT NOT NULL CHECK (
        char_length(nombre) BETWEEN 2 AND 64
    ),
    localidad CITEXT NOT NULL CHECK (
        char_length(localidad) BETWEEN 2 AND 64
        AND localidad ~ '^[a-zA-Z0-9-]+$' 
    ),
    codigo_postal INTEGER,
    UNIQUE(nombre, id_departamento),
    UNIQUE(localidad, id_departamento)
);

DROP TRIGGER IF EXISTS tg_localidades_localidad_inmutable ON localidades;
CREATE TRIGGER tg_localidades_localidad_inmutable
BEFORE UPDATE OF localidad ON localidades
FOR EACH ROW
EXECUTE FUNCTION tr_fn_impedir_cambio_columna('localidad');