CREATE TABLE IF NOT EXISTS credenciales (
    id_usuario UUID PRIMARY KEY REFERENCES usuarios(id_usuario) ON DELETE CASCADE ON UPDATE CASCADE,
    password_hash TEXT NOT NULL, -- Aquí sí es NOT NULL porque si existe la fila, hay clave.
    fecha_actualizacion TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS cuentas_externas (
    id_cuenta_externa INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,    
    id_usuario UUID NOT NULL REFERENCES usuarios(id_usuario) ON DELETE CASCADE ON UPDATE CASCADE,
    
    servidor AUTH_SERVER NOT NULL,
    id_externo VARCHAR(255) NOT NULL,   -- id que da servidor
    fecha_creacion TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP,
    
    UNIQUE(id_usuario, servidor),   -- Se permite solo una vez cada AUTH_SERVER para cada usuario
    UNIQUE(id_externo, servidor)    -- No se permite que se repita el id_externo para un mismo proveedor. No debería pasar, pero por las dudas.
);

CREATE TABLE public.refresh_tokens (
    jti UUID PRIMARY KEY, -- Esto es el randomUUID() que generaste
    id_usuario UUID NOT NULL REFERENCES public.usuarios(id_usuario) ON DELETE CASCADE ON UPDATE CASCADE, -- Si no es UNIQUE es que pueden haber varios refresh token para cada usuario.
    token_hash TEXT NOT NULL,
    expires_at TIMESTAMP WITH TIME ZONE NOT NULL,
    fecha_creacion TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP
);


-- //TODO: tabla para invalidar access_token ? No vale la pena, son muy cortos. Asegurarse que se borran del cliente.