CREATE TABLE IF NOT EXISTS usuarios (
    id_usuario UUID PRIMARY KEY DEFAULT uuidv7(),
    rol_actual ROL NOT NULL,                        -- Para guardar el último rol usado por el usuario
    roles ROL[] NOT NULL DEFAULT '{}',              -- Cuando se hace insert/update sobre productor/consumidor se agrega/quita el rol según el campo activo.
    fecha_creacion TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP,
    fecha_actualizacion TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP,
    fecha_eliminacion TIMESTAMP WITH TIME ZONE,
    activo BOOLEAN GENERATED ALWAYS AS (fecha_eliminacion IS NULL) STORED
);

-- Creamos una tabla aparte con los datos personales así sabemos que esto es lo que se debe borrar si el usuario se quiere dar de baja.
CREATE TABLE IF NOT EXISTS datos_personales (
    id_usuario UUID PRIMARY KEY REFERENCES usuarios(id_usuario) ON DELETE CASCADE ON UPDATE CASCADE, -- Misma clave que usuarios
    nombres VARCHAR(100),
    apellidos VARCHAR(100),
    email CITEXT UNIQUE CHECK (
        char_length(email) <= 254 AND 
        email ~* '^[a-z0-9._%+-]+@[a-z0-9.-]+\.[a-z]{2,}$'
    ),
    username CITEXT UNIQUE CHECK (
        char_length(username) BETWEEN 5 AND 20
        AND username ~ '^[a-zA-Z0-9-]+$' 
    ),
    celular VARCHAR(20) UNIQUE CHECK (celular ~ '^\+[1-9]\d{6,14}$'),
    foto_url TEXT,
    email_validado BOOLEAN NOT NULL DEFAULT false,
    celular_validado BOOLEAN NOT NULL DEFAULT false
);

CREATE TABLE IF NOT EXISTS ubicaciones (
    id_ubicacion INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    id_usuario UUID NOT NULL REFERENCES usuarios(id_usuario) ON DELETE CASCADE ON UPDATE CASCADE,
    id_localidad INTEGER NOT NULL REFERENCES localidades(id_localidad),
    
    nombre CITEXT NOT NULL CHECK (
        char_length(nombre) BETWEEN 2 AND 32
    ),
    ubicacion CITEXT CHECK (
        char_length(ubicacion) BETWEEN 2 AND 32
        AND ubicacion ~ '^[a-zA-Z0-9-]+$' 
    ),
    direccion TEXT NOT NULL,    -- Calle, número, entre calles, lo que quieran
    comentarios TEXT,
    -- 6 decimales es suficiente precisión.
    latitud NUMERIC(9, 6) CHECK (latitud BETWEEN -90 AND 90),
    longitud NUMERIC(9, 6) CHECK (longitud BETWEEN -180 AND 180),

    -- Columna PostGIS calculada de forma transparente
    -- OJO: ST_MakePoint recibe primero LONGITUD (X) y luego LATITUD (Y)
    punto GEOMETRY(Point, 4326) GENERATED ALWAYS AS (
        CASE 
            WHEN latitud IS NOT NULL AND longitud IS NOT NULL 
            THEN ST_SetSRID(ST_MakePoint(longitud, latitud), 4326)
            ELSE NULL 
        END
    ) STORED,
    
    fecha_creacion TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP,
    fecha_actualizacion TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP,

    UNIQUE(nombre, id_usuario),     -- Nombre no diferencia el case porque es tipo CITEXT
    UNIQUE(ubicacion, id_usuario)   -- idem anterior
);

CREATE INDEX IF NOT EXISTS idx_ubicaciones_punto ON ubicaciones USING GIST (punto);
CREATE INDEX IF NOT EXISTS idx_usuarios_roles ON usuarios USING GIN (roles);

CREATE TABLE IF NOT EXISTS productores (
    id_productor UUID PRIMARY KEY REFERENCES usuarios(id_usuario) ON DELETE CASCADE ON UPDATE CASCADE, -- Misma clave que usuarios
    presentacion TEXT NOT NULL,
    id_ubicacion INTEGER REFERENCES ubicaciones(id_ubicacion) ON DELETE CASCADE,
    calificacion SMALLINT CHECK (calificacion BETWEEN 1 AND 5), -- //TODO. Hacer trigger para cargar esto en base al promedio de calificaciónes de sus productos
    fecha_creacion TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP,
    fecha_actualizacion TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP,
    fecha_eliminacion TIMESTAMP WITH TIME ZONE,
    activo BOOLEAN GENERATED ALWAYS AS (fecha_eliminacion IS NULL) STORED
);

CREATE TABLE IF NOT EXISTS consumidores (
    id_consumidor UUID PRIMARY KEY REFERENCES usuarios(id_usuario) ON DELETE CASCADE ON UPDATE CASCADE, -- Misma clave que usuarios
    fecha_creacion TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP,
    fecha_actualizacion TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP,
    fecha_eliminacion TIMESTAMP WITH TIME ZONE,
    activo BOOLEAN GENERATED ALWAYS AS (fecha_eliminacion IS NULL) STORED
);


CREATE OR REPLACE FUNCTION fn_sincronizar_roles()
RETURNS TRIGGER AS $$
DECLARE
    v_rol ROL;
    v_id UUID; -- O INTEGER, según sea tu tipo de ID
BEGIN
    -- Determinar qué rol e id estamos manejando según la tabla que disparó el trigger
    IF TG_TABLE_NAME = 'productores' THEN
        v_rol := 'PRODUCTOR';
        v_id := CASE WHEN TG_OP = 'DELETE' THEN OLD.id_productor ELSE NEW.id_productor END;
    ELSIF TG_TABLE_NAME = 'consumidores' THEN
        v_rol := 'CONSUMIDOR';
        v_id := CASE WHEN TG_OP = 'DELETE' THEN OLD.id_consumidor ELSE NEW.id_consumidor END;
    END IF;

    IF (TG_OP = 'DELETE' OR (TG_OP = 'UPDATE' AND NEW.activo = FALSE)) THEN
        UPDATE usuarios 
        SET roles = array_remove(roles, v_rol)
        WHERE id_usuario = v_id;
    ELSIF (TG_OP = 'INSERT' OR (TG_OP = 'UPDATE' AND NEW.activo = TRUE)) THEN
        UPDATE usuarios 
        SET roles = array_append(array_remove(roles, v_rol), v_rol)-- Hacemos un remove antes por si las moscas
        WHERE id_usuario = v_id;
    END IF;

    RETURN NULL; 
END;
$$ LANGUAGE plpgsql;


-------------------------------------------------------------------
------------------ TRIGGERS PARA sincronizar roles ----------------
-------------------------------------------------------------------
CREATE OR REPLACE TRIGGER tr_sync_productores_lifecycle
AFTER INSERT OR DELETE ON productores
FOR EACH ROW 
EXECUTE FUNCTION fn_sincronizar_roles();

CREATE OR REPLACE TRIGGER tr_sync_productores_update
AFTER UPDATE OF activo ON productores
FOR EACH ROW 
WHEN (OLD.activo IS DISTINCT FROM NEW.activo)
EXECUTE FUNCTION fn_sincronizar_roles();

CREATE OR REPLACE TRIGGER tr_sync_consumidores_lifecycle
AFTER INSERT OR DELETE ON consumidores
FOR EACH ROW 
EXECUTE FUNCTION fn_sincronizar_roles();

CREATE OR REPLACE TRIGGER tr_sync_consumidores_update
AFTER UPDATE OF activo ON consumidores
FOR EACH ROW 
WHEN (OLD.activo IS DISTINCT FROM NEW.activo)
EXECUTE FUNCTION fn_sincronizar_roles();


-------------------------------------------------------------------
----------- TRIGGER PARA ACTUALIZAR fecha actualizacion -----------
-------------------------------------------------------------------
DROP TRIGGER IF EXISTS tg_usuarios_actualizar_fecha ON usuarios;
CREATE TRIGGER tg_usuarios_actualizar_fecha
BEFORE UPDATE ON usuarios
FOR EACH ROW
EXECUTE FUNCTION fn_actualizar_fecha_actualizacion();

DROP TRIGGER IF EXISTS tg_consumidores_actualizar_fecha ON consumidores;
CREATE TRIGGER tg_consumidores_actualizar_fecha
BEFORE UPDATE ON consumidores
FOR EACH ROW
EXECUTE FUNCTION fn_actualizar_fecha_actualizacion();

DROP TRIGGER IF EXISTS tg_productores_actualizar_fecha ON productores;
CREATE TRIGGER tg_productores_actualizar_fecha
BEFORE UPDATE ON productores
FOR EACH ROW
EXECUTE FUNCTION fn_actualizar_fecha_actualizacion();

DROP TRIGGER IF EXISTS tg_ubicaciones_actualizar_fecha ON ubicaciones;
CREATE TRIGGER tg_ubicaciones_actualizar_fecha
BEFORE UPDATE ON ubicaciones
FOR EACH ROW
EXECUTE FUNCTION fn_actualizar_fecha_actualizacion();


-------------------------------------------------------------------
------------------- RULES PARA hacer softdelete   -----------------
-------------------------------------------------------------------
CREATE OR REPLACE RULE r_usuarios_soft_delete AS
ON DELETE TO usuarios
DO INSTEAD
    UPDATE usuarios
    SET fecha_eliminacion = CURRENT_TIMESTAMP
    WHERE id_usuario = OLD.id_usuario AND fecha_eliminacion IS NULL;

CREATE OR REPLACE RULE r_consumidores_soft_delete AS
ON DELETE TO consumidores
DO INSTEAD
    UPDATE consumidores
    SET fecha_eliminacion = CURRENT_TIMESTAMP
    WHERE id_consumidor = OLD.id_consumidor AND fecha_eliminacion IS NULL;

CREATE OR REPLACE RULE r_productores_soft_delete AS
ON DELETE TO productores
DO INSTEAD
    UPDATE productores
    SET fecha_eliminacion = CURRENT_TIMESTAMP
    WHERE id_productor = OLD.id_productor AND fecha_eliminacion IS NULL;

-------------------------------------------------------------------
------------- TRIGGER PARA inmutabilidad de username --------------
-------------------------------------------------------------------
DROP TRIGGER IF EXISTS tg_datos_personales_username_inmutable ON datos_personales;
CREATE TRIGGER tg_datos_personales_username_inmutable
BEFORE UPDATE OF username ON datos_personales
FOR EACH ROW
EXECUTE FUNCTION tr_fn_impedir_cambio_columna('username');


-- //TODO: Trigger para que si cambia email en datos_personales setear email_validado en false
-- //TODO: Trigger para que si cambia celular en datos_personales setear celular_validado en false