--- RF-PP-01: El sistema debe permitir al usuario gestionar su catálogo de productos con nombre del producto, descripcion, precio, cantidad disponible y entre 1 y 5 fotos del producto, un video opcional ubicación de producción.
CREATE TABLE productos (
    id_producto INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    id_productor UUID NOT NULL REFERENCES productores(id_productor) ON DELETE CASCADE,
    id_subcategoria INTEGER NOT NULL REFERENCES subcategorias(id_subcategoria) ON DELETE RESTRICT,
    nombre CITEXT NOT NULL CHECK (
        char_length(nombre) BETWEEN 3 AND 35
    ), -- TODO: Regex para permitir solo letras y números ? No olvidarse eñes y acentos.
    producto CITEXT NOT NULL CHECK (
        char_length(producto) BETWEEN 3 AND 35
        AND producto ~ '^[a-zA-Z0-9-]+$' 
    ),-- TODO: TRIGGER para asegurarse que no se cambia el producto
    descripcion TEXT NOT NULL,
    precio DECIMAL(12, 2) NOT NULL,
    cantidad_disponible INTEGER NOT NULL DEFAULT 0,
    video_url TEXT,
    calificacion SMALLINT CHECK (calificacion BETWEEN 1 AND 5), -- TODO. Hacer trigger para cargar esto en base al promedio de calificaciónes recibidas en pedido_productos
    fecha_creacion TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP,
    fecha_actualizacion TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP,
    fecha_eliminacion TIMESTAMP WITH TIME ZONE,
    activo BOOLEAN GENERATED ALWAYS AS (fecha_eliminacion IS NULL) STORED,
    busqueda TSVECTOR GENERATED ALWAYS AS (
        setweight(to_tsvector('spanish'::regconfig, COALESCE(nombre, '')), 'A') ||
        setweight(to_tsvector('spanish'::regconfig, COALESCE(descripcion, '')), 'B')
    ) STORED,
    UNIQUE (id_productor, id_producto), -- Producto es entidad debil a Productor pero no es necesario que la PK sea compuesta. Hacemos esta clave para que pueda ser usada para las fk en otras tablas.
    UNIQUE (id_productor, nombre),      -- Para que un productor no pueda tener dos productos con el mismo nombre.
    UNIQUE (id_productor, producto)-- Para que un productor no pueda tener dos productos con el mismo slug.
);
-- TODO: Trigger para actualizar la calificación el productor en base al promedio  de calificaciones del producto
-- Indice para búsquedas avanzadas con el campo busqueda
CREATE INDEX productos_busqueda_idx ON productos USING GIN (busqueda);

CREATE TABLE producto_etiquetas (
    id_producto INTEGER NOT NULL,
    id_etiqueta INTEGER NOT NULL REFERENCES etiquetas(id_etiqueta) ON DELETE CASCADE,
    -- TODO: Trigger para asegurarse que la etiqueta está dentro de las permitidas.
    PRIMARY KEY (id_producto, id_etiqueta),
    CONSTRAINT producto_etiquetas_producto_fk FOREIGN KEY (id_producto) REFERENCES productos(id_producto) ON DELETE CASCADE
);

CREATE TABLE producto_imagenes (
    id_producto INTEGER NOT NULL,
    posicion SMALLINT NOT NULL CHECK (posicion BETWEEN 1 AND 5),
    path CITEXT NOT NULL, --path relativo

    PRIMARY KEY (id_producto,posicion),
    FOREIGN KEY (id_producto) REFERENCES productos(id_producto) ON DELETE CASCADE
);
