--- RF-PP-01: El sistema debe permitir al usuario gestionar su catálogo de productos con nombre del producto, descripcion, precio, cantidad disponible y entre 1 y 5 fotos del producto, un video opcional ubicación de producción.
CREATE TABLE productos (
    -- Entidad debil a productor. Por eso clave compuesta y delete cascade.
    id_productor UUID NOT NULL REFERENCES productores(id_usuario) ON DELETE CASCADE,
    id_producto BIGINT GENERATED BY DEFAULT AS IDENTITY,
    id_subcategoria INTEGER NOT NULL REFERENCES subcategorias(id_subcategoria),
    
    nombre TEXT NOT NULL,
    descripcion TEXT NOT NULL,
    precio DECIMAL(12, 2) NOT NULL,
    cantidad_disponible INTEGER NOT NULL DEFAULT 0,
    
    fotos TEXT[] NOT NULL CHECK (cardinality(fotos) BETWEEN 1 AND 5),
    video_url TEXT,
    
    fecha_creacion TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP,
    fecha_actualizacion TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP,

    PRIMARY KEY (id_productor, id_producto)
);

CREATE TABLE producto_etiquetas (
    id_productor UUID NOT NULL,
    id_producto BIGINT NOT NULL,
    id_etiqueta INTEGER NOT NULL REFERENCES etiquetas(id_etiqueta) ON DELETE CASCADE,
    -- TODO: Trigger para asegurarse que la etiqueta está dentro de las permitidas.
    PRIMARY KEY (id_productor, id_producto, id_etiqueta),
    
    CONSTRAINT producto_etiquetas_producto_fk FOREIGN KEY (id_productor, id_producto) REFERENCES productos(id_productor, id_producto) ON DELETE CASCADE
);

